### PR TITLE
Fix list update

### PR DESCRIPTION
**Pull request by NickDJM**
Updates to allow all lists to be updated when one mutates.

### CODE REVIEW

**Review by DaveBagler — APPROVED** [review]

**Review by budimanc — COMMENTED** [review]
It works when we move it one level down but not when it's more (for example from 4th level to 1st level); but you may want double check with @VennilaCity if that's part of the requirements.

**Comment by NickDJM** [comment]
@budimanc Any specific browser/OS? I'm able to move list items 4 levels and everything seems to update just fine.

**Comment by budimanc** [comment]
@NickDJM It works on all levels for Firefox 63.0.3 but only one level for Chrome 70.0.3538.102 (Win 10 - Build 17134)

**Comment by NickDJM** [comment]
@budimanc Can you make sure your cache is cleared? I can't reproduce the bug you're seeing.

**Comment by budimanc** [comment]
@NickDJM I did and confirmed I pulled the js with your new change.    Based on @elcazador comment yesterday (https://github.com/CityofOttawa/ottawa_profile/issues/2341#issuecomment-444144716) it seems he may run into the same bug.

**Comment by DaveBagler** [comment]
@NickDJM, @budimanc, what's happening with this issue now?

**Comment by budimanc** [comment]
@DaveBagler @NickDJM I'm merging this first so this fix will get included in QA.   Although the prior one seems to be approved already https://github.com/CityofOttawa/ottawa_profile/issues/2341#issuecomment-444534629

**Pull request merged**
